[package]
name = "fedex-vst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[workspace]
members=["start", "distortion", "popback-shift", "popback-shift-reverse", "scuffed-octave"]