[package]
name = "popback-shift"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="popback_shift"
crate-type=["cdylib"]

[dependencies]
vst={ git = "https://github.com/rustaudio/vst-rs" }